spring:
  application:
    name: mongo-app
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: example
  datasource:
    url: jdbc:mongodb://localhost:27017/example
    driver-class-name: com.dbschema.MongoJdbcDriver
  flyway:
    url: jdbc:mongodb://localhost:27017/example
    driver-class-name: com.dbschema.MongoJdbcDriver
    environment: "mongodb"
    fail-on-missing-locations: true
    locations: classpath:db/migration
    sqlMigrationSuffixes:
      - ".js"
    enabled: true